path="/your/path/to/Recon-Bash-Functions-Linux"

source "${path}/line_count.sh"
source "${path}/welcome.sh"
source "${path}/print_color.sh"
source "${path}/find_subdomains_by_waybackurls.sh"
source "${path}/find_subdomains_by_tools.sh"
source "${path}/find_subdomains_by_providers.sh"
source "${path}/find_subdomains_by_crawlers.sh"
source "${path}/find_subdomains_by_certificate.sh"
source "${path}/hook_test.sh"
